# LIBVISO2 PARAMETERS

stereo_odometer:

  # IMAGE PARAMETERS:
  # Original LIBVISO2
  half_resolution: 0
  # LIBVISO2-ROS
  queue_size: 5
  approximate_sync: true

  # FRAME PARAMETERS:
  # LIBVISO2-ROS
  base_link_frame_id: '/turbot/base_link'
  sensor_frame_id: '/turbot/stereo_down/left_optical'

  # VERSION PARAMETERS:
  # LIBVISO2-ROS-Modified
  detection_and_matching_version: 0 # 0=Original LIBVISO2, 1=SIFT-SIFT, 2=SURF-SIFT, 3=SURF-BRISK, 4=SURF-FREAK

  # FEATURE DETECTION PARAMETERS:
  # Original LIBVISO2
  nms_n: 3
  nms_tau: 3
  # LIBVISO2-ROS-Modified
  contrastThreshold_SIFT: 0.03
  edgeThreshold_SIFT: 10
  sigma_SIFT: 1.6
  hessianThreshold_SURF: 500
  nOctaves_SURF: 4
  nOctaveLayers: 3

  # FEATURE MATCHING PARAMETERS:
  # Original LIBVISO2
  match_binsize: 50
  match_radius: 200
  match_disp_tolerance: 1 
  multi_stage: 1
  refinement: 1

  # OUTLIER REJECTION PARAMETERS:
  # Original LIBVISO2
  outlier_disp_tolerance: 5
  outlier_flow_tolerance: 5
  # LIBVISO2-ROS-Modified
  homography_reprojThreshold: 3
  epipolar_constrain: 1

  # BUCKETING PARAMETERS:
  # Original LIBVISO2
  max_features: 2
  bucket_width: 50
  bucket_height: 50
  # LIBVISO2-ROS-Modified
  enable_bucketing: false

  # MOTION ESTIMATION PARAMETERS:
  ransac_iters: 300
  inlier_threshold: 1

  # ALTITUDE CONTROL:
  assinged_altitude: 2.5 # Altitude from which movement calculation is to be started 